import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { SmtpClient } from "https://deno.land/x/smtp@v0.7.0/mod.ts";

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const { customerName, items } = await req.json()

        const client = new SmtpClient();

        // 1. Connect to Outlook
        await client.connectTLS({
            hostname: "smtp-mail.outlook.com",
            port: 587,
            username: Deno.env.get("OUTLOOK_EMAIL"),
            password: Deno.env.get("OUTLOOK_APP_PASSWORD"),
        });

        // 2. Build HTML List
        const terms = items.map((item: any) =>
            `<li><b>${item.product}</b>: ${item.qty} units</li>`
        ).join('');

        // 3. Compose Email
        const emailBody = `
      <h3>New Sales Order Created</h3>
      <p><b>Customer:</b> ${customerName}</p>
      <p><b>Items:</b></p>
      <ul>${terms}</ul>
      <p><i>Auto-generated by Admixtures Buddy</i></p>
    `;

        // 4. Send
        // Note: You can add more recipients in the 'to' array or 'cc'
        await client.send({
            from: Deno.env.get("OUTLOOK_EMAIL"),
            to: "mo.hassan.1821@gmail.com", // TARGET EMAIL (Can be dynamic)
            subject: `New Order: ${customerName}`,
            content: emailBody,
            html: emailBody,
        });

        await client.close();

        return new Response(
            JSON.stringify({ message: 'Email sent successfully' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )

    } catch (error) {
        return new Response(
            JSON.stringify({ error: error.message }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
        )
    }
})
